[[extensions]]
name = "AdBlock Plus"
url = "https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb"

[[extensions]]
name = "Grammarly"
url = "https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen"

[[extensions]]
name = "LastPass"
url = "https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd"

[[extensions]]
name = "uBlock Origin"
url = "https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm"

[[extensions]]
name = "Evernote Web Clipper"
url = "https://chrome.google.com/webstore/detail"

[[extensions]]
name = "Google Translate"
url = "https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb"

[[extensions]]
name = "Save to Pocket"
url = "https://chrome.google.com/webstore/detail/save-to-pocket/niloccemoadcdkdjlinkgdfekeahmflj"

[[extensions]]
name = "Awesome Screenshot"
url = "https://chrome.google.com/webstore/detail/awesome-screenshot/nlipoenfbbikpbjkfpfillcgkoblgpmj"

[[extensions]]
name = "OneTab"
url = "https://chrome.google.com/webstore/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall"

[[extensions]]
name = "The Great Suspender"
url = "https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg"

[[extensions]]
name = "StayFocusd"
url = "https://chrome.google.com/webstore/detail/stayfocusd/laankejkbhbdhmipfmgcngdelahlfoji"

[[extensions]]
name = "RescueTime"
url = "https://chrome.google.com/webstore/detail/rescuetime/bmnlcjabgnpnenekpadlanbbkooimhnj"

[[extensions]]
name = "Boomerang for Gmail"
url = "https://chrome.google.com/webstore/detail/boomerang-for-gmail/mdanidgdpmkimeiiojknlnekblgmpdll"

[[extensions]]
name = "Todoist"
url = "https://chrome.google.com/webstore/detail/todoist-to-do-list-task-l/jldhpllghnbhlleeobkclaookdhncomo"

[[extensions]]
name = "Buffer"
url = "https://chrome.google.com/webstore/detail/buffer/noojglkidnpfjbincgijbaiedldjfbhh"

[[extensions]]
name = "Hootsuite Hootlet"
url = "https://chrome.google.com/webstore/detail"

[[extensions]]
name = "Full Page Screen Capture"
url = "https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl"

[[extensions]]
name = "Grammarly for Microsoft Office"
url = "https://chrome.google.com/webstore/detail/grammarly-for-microsoft-o/eljapbgkmlngdpckoiiibecpddcmgdlh"

[[extensions]]
name = "Tampermonkey"
url = "https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo"

[[extensions]]
name = "Wappalyzer"
url = "https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg"

[[extensions]]
name = "Postman"
url = "https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop"

[[extensions]]
name = "Diigo"
url = "https://chrome.google.com/webstore/detail/diigo-web-collector-captu/pnhplgjpclknigjpccbcnmicgcieojbh"

[[extensions]]
name = "Yoroi"
url = "https://chrome.google.com/webstore/detail/yoroi/ffnbelfdoeiohenkjibnmadjiehjhajb"

[[extensions]]
name = "Metamask"
url = "https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related"

[[extensions]]
name = "dictionay"
url = "https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja"

[[extensions]]
name = "Nami wallet"
url = "https://chrome.google.com/webstore/detail/nami/lpfcbjknijpeeillifnkikgncikgfhdo"

[[extensions]]
name = "Google Docs"
url = "https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi/related"

[[extensions]]
name = "Picture-in-Picture extension"
url = "https://chrome.google.com/webstore/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg/related?hl=en"


