[[url_list]]
  name = "flux"
  url = "https://justgetflux.com/"

[[url_list]]
  name = "Git, a distributed version control system for software development"
  url = "https://git-scm.com/download/win"

[[url_list]]
  name = "Git GUI"
  url = "https://www.sourcetreeapp.com/"

[[url_list]]
  name = "Software for the Arduino platform"
  url = "https://www.arduino.cc/en/software"

[[url_list]]
  name = "Sublime Text, a popular text editor"
  url = "https://www.sublimetext.com/download"

[[url_list]]
  name = "Ninite, a website that allows you to easily download multiple popular software programs"
  url = "https://ninite.com/"

[[url_list]]
  name = "Anaconda, a distribution of the Python and R programming languages"
  url = "https://www.anaconda.com/"

[[url_list]]
  name = "Telegram, a messaging app"
  url = "https://telegram.org/apps"

[[url_list]]
  name = "Signal, a secure messaging app"
  url = "https://signal.org/download/windows/"

[[url_list]]
  name = "WhatsApp, a messaging app"
  url = "https://www.whatsapp.com/download"

[[url_list]]
  name = "Viber, a messaging app"
  url = "https://www.viber.com/en/download/"

[[url_list]]
  name = "MetaTrader 4, a trading platform for forex and other financial markets"
  url = "https://www.metatrader4.com/en"

[[url_list]]
  name = "PyCharm, an integrated development environment (IDE) for Python"
  url = "https://www.jetbrains.com/pycharm/download"

[[url_list]]
  name = "Brave, a web browser"
  url = "https://brave.com/download/"

[[url_list]]
  name = "Visual Studio Code, a text editor and integrated development environment (IDE)"
  url = "https://code.visualstudio.com/download"

[[url_list]]
  name = "Private Internet Access, a virtual private network (VPN) service"
  url = "https://www.privateinternetaccess.com/download/windows-vpn"

[[url_list]]
  name = "Slack, a communication and collaboration platform"
  url = "https://slack.com/intl/en-au/download"

[[url_list]]
  name = "Exodus, a cryptocurrency wallet"
  url = "https://www.exodus.com/download/"

[[url_list]]
  name = "Malyware bytes, protection for PC"
  url = "https://www.malwarebytes.com/mwb-download/thankyou"




[[url_list]]
  name = "Plex, media server"
  url = "https://www.plex.tv/media-server-downloads/?lang=en-au#plex-app"

[[url_list]]
  name = "Rescue Time"
  url = "https://www.rescuetime.com/download"

[[url_list]]
  name = "Postman, a tool for API development and testing"
  url = "https://www.postman.com/downloads/"

[[url_list]]
  name = "Speed reading"
  url = "https://s3.amazonaws.com/flexframework/7SpeedReadingEX/7sr-ex-2019.0.1-main-win.exe"

[[url_list]]
  name = "Anki - flash card reader"
  url = "https://apps.ankiweb.net/"

[[url_list]]
  name = "Microsoft Teams"
  url = "https://www.microsoft.com/en-au/microsoft-teams/download-app#desktopAppDownloadregion"

[[url_list]]
  name = "Node JS"
  url = "https://nodejs.org/en/"

[[url_list]]
  name = "Garmin - GPS"
  url = "https://www.garmin.com/en-AU/software/express/windows/"

[[url_list]]
  name = "QGIS"
  url = "https://www.qgis.org/en/site/forusers/download.html#"

[[url_list]]
  name = "Trading View"
  url = "https://www.tradingview.com/desktop/"

[[url_list]]
  name = "Docker"
  url = "https://www.docker.com/products/docker-desktop/"

[[url_list]]
  name = "HWIFO - PC hardware Monitoring"
  url = "https://www.hwinfo.com/download/"

[[url_list]]
  name = "Chocolatey"
  url = "https://chocolatey.org/install"

[[url_list]]
  name = "Samsung Installer"
  url = "https://semiconductor.samsung.com/consumer-storage/support/tools/"

[[url_list]]
  name = "Tableau Public"
  url = "https://www.tableau.com/en-us/downloads/public/pc64"

[[url_list]]
  name = "R studio"
  url = "https://posit.co/download/rstudio-desktop/"

[[url_list]]
  name = "Speccy"
  url =  "https://www.ccleaner.com/download"

[[url_list]]
  name = "Thonny - small python program"
  url = "https://thonny.org/"

[[url_list]]
  name = "OBS Studio - video capture"
  url = "https://obsproject.com/download"

[[url_list]]
  name = "Insta360 - video processing "
  url = "https://www.insta360.com/download"

[[url_list]]
  name = "Blackmagic Design - DaVinci Resolve - video processing"
  url = "https://www.blackmagicdesign.com/au/products/davinciresolve"

[[url_list]]
  name = "Notion - Productivity"
  url = "https://www.notion.so/download"

[[url_list]]
  name = "Inkscape - Vector Art"
  url = "https://inkscape.org/release/inkscape-1.3.2/windows/64-bit/msi/?redirected=1"

[[url_list]]
  name = "Kindle - ebook reading"
  url = "https://www.amazon.com/b?ie=UTF8&node=16571048011"

[[url_list]]
  name = "AZDOME - GPS dashcam video"
  url = "http://forum.azdome.hk/forum.php?mod=viewthread&tid=737&page=1&extra=#pid966"

[[url_list]]
  name = "Gplates - earth software"
  url = "https://www.gplates.org/download/"

[[url_list]]
  name = "Personal apps on your work PC"
  url = "https://portableapps.com/"

[[url_list]]
  name = "FreeCAD, downloads"
  url = "https://www.freecad.org/downloads.php"

[[url_list]]
  name = "Draw.io Desktop, release v24.4.0"
  url = "https://github.com/jgraph/drawio-desktop/releases/tag/v24.4.0"

  name = "LM Studio"
  url = "https://lmstudio.ai/"

  name = "AnythingLLM"
  url = "https://anythingllm.com/"

  name = "GitHub Desktop"
  url = "https://desktop.github.com/download/"
